# From: https://github.com/jycouet/svienna_22_10/blob/master/playwright.config.ts
name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      ## Special action doing all the setup, thx The Guild!
      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 16
          packageManager: pnpm

      ## Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 29
